version: '3.5'
services:
  client:
    container_name: client
    build:
      context: ../client
      dockerfile: ../docker/client.Dockerfile
    volumes:
       - ../client/src:/home/dockeruser/project/src
    ports:
     - "80:4200"
